### ISSUE TITLE
Add new licenses

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#1]
Improve the script with new opensource licenses.

**Comment by srisankethu** [comment]
Can i try it? I have just gone through the README. The project looks interesting. Can you assign me?

**Comment by Mte90** [comment]
sure :-)
on github I can assign only to member of the repo, but no worry this ticket is your :-)

**Comment by rajibmitra** [comment]
Hi , Could you please tell how "badge" is working here , when I am clicking the link , it gives me "I have nothing to offer for this request"  
def downloadLicense(url, name, badge):

**Comment by Mte90** [comment]
As you can see in the readme of the project there is a badge.
Is very simple is an image so with markdown i add the link of the online version of the badge.

**Comment by rajibmitra** [comment]
yeah , right , but lets say I want to add below licenses (OSI approved) , I got the url and name , but how can I convert it to shield.io , sorry for the lame question !!
[license.txt](https://github.com/Mte90/GH-License/files/497705/license.txt)

**Comment by Mte90** [comment]
Well after a little discovery how work shelds.io is very easy:

https://img.shields.io/badge/License-GPL%20v4-blue.svg

The first part specifity the first text, the second the license name and last the color that is blue for licenses.

**Comment by rajibmitra** [comment]
Cool !! Thanks !

**Comment by Mte90** [comment]
Ok new license avalaible!
