### ISSUE TITLE
Support for GitLab, BitBucket

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#15]
The script born for GitHub but support other services is important.
The script check a profile for all the repos and search in all of them for a license file.
Is hardcoded the support for GitHub but probably with only a switch of the domain works also with other services.

**Comment by alberthdev** [comment]
@Mte90 I'm interested in helping out! GitLab might be tricky due to the nature of the API (it's currently in development at the moment), but I can work on BitBucket integration. Anything I should know before starting?

**Comment by Mte90** [comment]
As you can see in the code is very easy because I do only a check if the url exist for every file
