### ISSUE TITLE
Git hooks

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#21]
It will be helpful to have a git hooks installed globally when is executed `git init` to remember to download a license.

**Comment by revolter** [comment]
There is no `git init` hook. How would you want to do it?

**Comment by Mte90** [comment]
You are right seems that `git init` copy only the hooks when it is executed.
Probably the best way is to create a hook that is executed at every commit that check if in the repo there is a license file and after the creation remove itself to avoid multiple executions.

**Comment by revolter** [comment]
Does this software already have the license presence checking logic?

And does this software create licenses too? If yes, how would it know what license to create?

**Comment by Mte90** [comment]
I suggest to you to read the readme :-)
Actually doesn't have a logic to check if in the folder exist the license (has the logic to check if exist online so maybe split the code can be an idea).
For the rest check the readme :-)

**Comment by revolter** [comment]
From what I see, you have to specify the license. Or by

> after the creation

you meant after the user creates the license using the software?

**Comment by Mte90** [comment]
Yes this is the purpose of the software :-)

**Comment by revolter** [comment]
I know, I originally thought you meant that the git hook should create the license. I'm sorry if I look ignorant, I just want to help with this even though I never used this software.

**Comment by Mte90** [comment]
No worry but the best way is to try it :-)
Check the readme and try it so you can check what is doing :-)

**Comment by revolter** [comment]
I will after I start working on this 😄 

I think [this](https://gist.github.com/carlos-jenkins/89da9dcf9e0d528ac978311938aade43) is the best way to accomplish this.

**Comment by Mte90** [comment]
Yes can be an idea probably the hook pre-commit is the best so it is possible to bloc kthe commit without a license file in the repo.
