### ISSUE TITLE
Improve the code organization

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#22]
Divide the code in more file or more functions with comments can improve the code quality

**Comment by TheCodeArtist** [comment]
Going through the py files, commenting with some restructuring looks like something i can do this weekend.

@Mte90 Can you assign this issue to me?...

**Comment by Mte90** [comment]
I assigned to myself but I added you as collaborator so when you accept I switch that.
In any case if you take more then a week I will remove the assignee to let others to do it :-)

**Comment by pradyunsg** [comment]
I would be interested in taking this on too. :)

**Comment by Mte90** [comment]
You have to wait for @TheCodeArtist or in case work on the other ticket (or propose new features and develop it)

**Comment by pradyunsg** [comment]
Okie. :)

**Comment by EnriqueLazcorreta** [comment]
I think that, in ghlicense/cmd.py, the license selection code (lines 198 to 225) could be replaced by the statements

licenses = {'GPLv2': ("http://www.gnu.org/licenses/gpl-2.0.txt", '(https://img.shields.io/badge/License-GPL%20v2-blue. svg)] (https://img.shields.io/badge/License-GPL%20v2-blue.svg)),
                   'GPLv3': (...),
                   ...}
license = licenses.get (args.license, None)

if license:
     downloadLicense (license [0], args.license, license [1])
else:
     print ('License not found!')

By doing so you could read the dictionary `licenses` from file, facilitating the task of managing the licenses known by the script (issue # 1, Add new licenses).

**Comment by Mte90** [comment]
I think that you can do a pr for that in the meantime, don't forget if we want to remove the mention of licenses in the code is important to add in the new file also the description that is used by another method :-)

**Comment by EnriqueLazcorreta** [comment]
I'm a beginner in git, I'll see what can I do.

**Comment by TheCodeArtist** [comment]
@Mte90 Here are the changes i've in mind after reviewing the code:

For the first pass, today i plan to submit a PR with commits that do the following:

1. Add docstrings for the module and each function
2. Rename the following functions more descriptively as:
  - makeprint() --> printStatus()
  - progressbar --> updateProgressBar()
  - downloadLicense --> updateLicense()
3. Update the LICENSE addition commit msg with name of the license.

Next i can then work on adding inline commentary for the several non-obvious sections in code.

**Comment by Mte90** [comment]
Amazing!
Evaluate what is the best way for you if different pull requests or only one!
I will be here waiting like a kid waiting for santa claus :-D

**Comment by TheCodeArtist** [comment]
Done.

Please review commits: 9a6c414172980d1a08c8d9444843cc752de126ca and d59292a5f81b8b32edf596ce8834beb061c9f858.

However i learnt a new "catch" during this git+github flow.

Cloing my fork of this repo and attempting to push to my fork using `git push origin HEAD:master` resulted in pushing changes to this repo itself (and NOT my fork!) 

The explanation for this behaviour appears to be the fact that all github forks continue to list origin as  this original repo, Thus git push defaults to this repo as explained [**here**](https://stackoverflow.com/a/25546211/319204).

I've updated my local git repo to point to my Github fork. Any `git push` now will push changes onto my fork on Github and then i can follow the usual flow of raising a Pull-Request to this repo.

**Comment by TheCodeArtist** [comment]
Here is my plan for the next set of changes that i shall submit tomorrow as a "Pull-Request"

**4. Understand and comment (or fix) good/bad list of providers** 
Please respond to https://github.com/Mte90/GH-License/issues/25 at your convenience,
so that i can update the code/documentation approriately.

**5. Comment/Fix cmdline param check**
https://github.com/Mte90/GH-License/blob/8f7eb89113ba436ac087ca3eace3993e71df4293/ghlicense/cmd.py#L49-L52

Am considering udpating the comment to...
```
# Check whether atleast 1 cmdline param was passed to the script.
# If not then display help/usage and quit.
```

6. Add inline commentary for updateLicense() using #comments. 

7. Add inline commentary for main() using #comments.

**Comment by TheCodeArtist** [comment]
Submitted [**PR28**](https://github.com/Mte90/GH-License/pull/28) addressing steps 4 through 7.

Please review.

**Comment by TheCodeArtist** [comment]
Okay. Now that PR28 is merged, what else is left out in this issue?

Along the lines of what EnriqueLazcorreta mentioned above,  
how about moving out the licenses info into a JSON file?

Thus license and licenselist flows become simple loops that iterate over a list 
(the list generated simply by `json.load`-ing the `known-licenses.json` file).

Plus its becomes easier to add/modify license links/info.

I'm not clear about the steps to add a JSON file to a python package.  
Is it sufficient to follow the steps mentioned [**here**](http://python-packaging.readthedocs.io/en/latest/non-code-files.html)?...

**Comment by Mte90** [comment]
Yes it is the way :-)

**Comment by EnriqueLazcorreta** [comment]
I think that `known-licenses.json` file could be loaded (or linked, better than cloned) from https://github.com/sdgluck/oss-licenses using some strategy to know synonymous of the names @Mte90 use. I don't know if there are "standard" names for the acronyms of licenses, do you know?

There are a lot of projects about licenses: https://github.com/search?utf8=✓&q=licenses It's not necessary to create and to maintain yet another one... ;-)

**Comment by Mte90** [comment]
Standard names doesn't exist only for the file license files have a standard names. There are a lot of projects for licenses but not for add in the projects already exist.

**Comment by EnriqueLazcorreta** [comment]
Agree. Anyway, even if there are standards your application has to use the names/acronyms used in github and bitbucket (and any other vendors you add).

@srisankethu is in charge of adding new licenses, he should participate in this thread or we should move it to issue # 1.

Can I develop the json file loading or has @TheCodeArtist working on this issue?

**Comment by TheCodeArtist** [comment]
>Can I develop the json file loading or has @TheCodeArtist working on this issue?
I haven't started working on it.
I vote we discuss and follow-up the License handling in its own issue.

Unless there are any other changes planned we can then mark this issue closed.

What do you say @Mte90 ?

**Comment by Mte90** [comment]
yes for me is fine :-D

**Comment by revolter** [comment]
I think that #27 should wait for the license handling refactoring too, right? So we won't have to fix conflicts.

**Comment by Mte90** [comment]
I think that now it is possible to think about a code organization more modular if needed with all the new features and improvements made by you guys :-D

**Comment by Mte90** [comment]
I removed the assignee waiting for a new one that want to organize better the code in different files.
