### ISSUE TITLE
Remember the last used license

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#23]
Actually when you use the tool you have to remember the last license or what you use mostly with the codename used in the package.
It will be cool to remind what are the most used on creating when the license is not specified with a prompt to ask to the user what of the license most used want to use.

**Comment by rivergillis** [comment]
Hi! This seems interesting. So the flow would look something like:
`$ gh-license --license`
`> Please enter a license. Some common licenses are MIT, GPLv3, [and so on]`
`> MIT`
At this point the script goes on as if the user called the script using
`$ gh-license --license MIT`

Is this what you're suggesting?

**Comment by Mte90** [comment]
I was thinking something like
```
$ gh-license --license
> You not chosen a license, the last one you used is MIT[1], GPLv3 [2] [and so on]
> Press 1,2,[and so on] to download one of this license or [n] to see the description of all of them 
```
Because actually when you use --license without parameter there is the description of all of them

**Comment by rivergillis** [comment]
Sounds good, so as far as storing the previously used licenses, the script could generate and read from some `ghlprops` (GH-License properties) file. It could be a json file with a structure sort of like
```
{
    "lastUsed": [
        "MIT",
        "GPLv3"
    ]
}
```

Unless you think that'd be overkill.

**Comment by Mte90** [comment]
yes a file where to save that information is required :-)

**Comment by rivergillis** [comment]
I can go ahead and pack it into a comma delimited string under a `[lastUsed]` section in that file then.
