### ISSUE TITLE
Can there ever be any provider in the "bad" list?

### ISSUE THREAD

**Issue by TheCodeArtist** [Mte90/GH-License#25]
https://github.com/Mte90/GH-License/blob/70cb31f657d76ede1a8704b26bc815ed698cd598/ghlicense/repobase.py#L44-L49

With the above logic, 
under what circumstances will a provider be added to the "bad" list?...

**Comment by Mte90** [comment]
Checking the code in the class the bad providers are defined in the rest of methods. If the class of the methods ins not available or is not working is bad and not loaded

**Comment by TheCodeArtist** [comment]
I was (still am) confused by the following...

https://github.com/Mte90/GH-License/blob/8f7eb89113ba436ac087ca3eace3993e71df4293/ghlicense/repobase.py#L45-L49

If `"Loaded" = False`, the provider is being set to `None`.
So,  next when we iterate over the list of providers using

https://github.com/Mte90/GH-License/blob/8f7eb89113ba436ac087ca3eace3993e71df4293/ghlicense/repobase.py#L70-L74

wouldn't the `bad` be simply a list of `None`?

----

Its obvious to me now that i do not understand Python lists as well as i thought i did 😀 😁

I suppose i will 
- locally modify the call `repobase.register_provider()` with `Loaded` = `False`
- and step through `get_providers()` in a graphical debugger like Pycharm 
to understand what happens.

**Comment by TheCodeArtist** [comment]
With the help of the Pycharm graphical debugger, i think i got the hang of it.

![image](https://user-images.githubusercontent.com/1897177/31043086-7456ef42-a5d3-11e7-9ad9-c8db351231ce.png)

`providers` is essentially a **`dict`**. The for loop in `get_providers()` uses the `name` as an index to iterate over all registered providers.

A provider that has called `repobase.register_provider()` with `Loaded` = `False` shall have its corresponding entry in `providers` set to `None`. However this entry DOES exist and can be referenced within the `providers` dict using the `name`.

Time to incorporate this explanation in brief using inline comments in `repobase.py` 😀
