### ISSUE TITLE
Improve License suggestion help

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#3]
Actually this is the output:
``First parameter is missing: The license: GPLv2, GPLv3, LGPLv3, AGPLv3, FDLv1.3, Apachev2, CC-BY
``

Add a list with all the licenses with an explanation will be useful to choice.

**Comment by swapsharma** [comment]
I will like to give it a try. Can you assign me?

**Comment by Mte90** [comment]
I can assign only on people of the organization of the repo so I cannot :-/
Start to work on it and no worry about the assign

**Comment by rajibmitra** [comment]
Hi, Do you want a list to hold all the licenses with explanation ?

**Comment by Mte90** [comment]
yes in the help will be very useful for the choice

**Comment by essank** [comment]
I like your project and I would like to help @Mte90

**Comment by Mte90** [comment]
well start to work on the ticket :-)
