### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by Mte90** [Mte90/GH-License#30]
* https://www.codacy.com/app/mte90/GH-License/issues

**Comment by revolter** [comment]
Should we adhere to [PEP 8](https://www.python.org/dev/peps/pep-0008) too? I have a vim plugin installed which warns me about a lot of issues in `cmd.py`.

**Comment by Mte90** [comment]
Uhm we can work to improve also this alerts on codacy with a config file for pylint.

**Comment by tkindy** [comment]
I can take this issue!
