### ISSUE TITLE
Fix broken character

### ISSUE THREAD

**Issue by revolter** [Mte90/GH-License#31]
This line:

https://github.com/Mte90/GH-License/blob/1290856a61070ab00f29ea1650c63d39b7f6e0c5/ghlicense/cmd.py#L280

has a character which can't be displayed for me on macOS High Sierra, neither in terminal, nor the browser:

![screen shot 2017-10-07 at 00 36 17](https://user-images.githubusercontent.com/5748627/31299539-8ea7364e-aaf7-11e7-9fcc-638da4d947f2.png)

Is this happening only for me? What character should it be?

**Comment by Mte90** [comment]
Probably in the meantime the char broken, we can replace with a `!`
