### ISSUE TITLE
Raising IndexError on empty README file

### ISSUE THREAD

**Issue by B3QL** [Mte90/GH-License#5]
`touch README.md`
`python gh-license.py --license GPLv2`

> Traceback (most recent call last):
  File "gh-license.py", line 69, in <module>
    downloadLicense("http://www.gnu.org/licenses/gpl-2.0.txt", args.args[0], '(https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://img.shields.io/badge/License-GPL%20v2-blue.svg)')
  File "gh-license.py", line 26, in downloadLicense
    if text[0][0] == '#':
IndexError: list index out of range

**Comment by Mte90** [comment]
Thank you to @yurimalheiros this is fixed
